### ISSUE TITLE
CSS Comment

### ISSUE THREAD

**Issue by jim-rosales** [generalni/teacozy#4]
Nice job including a comment to explain your implementation! Next time consider commenting the rest of your sections as well.

For example:
```CSS
/** Universal Styles **/
* {
	padding: 0;
	margin: 0;
	color: seashell;
	font-size: 22px;
	opacity: 0.9;
	text-align: center;
	font-family: Helvetica, sans-serif;
}

body {
	background-color: black;
}
```

https://github.com/generalni/teacozy/blob/ef4af1c5e8976e988fa67fcd4ac0873ae1355df4/resources/css/style.css#L68
